"""ID Telegram стикеров."""

RESISTANCE_DOG_ID = (
    "CAACAgIAAxkBAAIHOGlj4mUESSCX2kEwhOmWglNuMRbLAALhAANWnb0KW8GUi0D406A4BA"
)
SHAITAN_CHICK_ID = (
    "CAACAgIAAxkBAAIHTmlj5zCc_aY4k490Rp1PnV4gomuFAAKIAANEDc8XRY1vLDzXl_44BA"
)
BODJELLYFISH_ID = (
    "CAACAgIAAxkBAAIHYWlj6H0S7mkJtwkS8OmP3Oey2_eAAAJeAAPANk8TD4PNEIK9PE04BA"
)
MR_CAT_ID = "CAACAgIAAxkBAAIHg2lj6ZgcEqe8NUxAZ0Z4QI-dMrM3AAJHAANZu_wlXJ3WrE3fYSw4BA"
PANDA_EMIC_ID = (
    "CAACAgIAAxkBAAIHhWlj6kdDo8nOBnjzfg64u0iABQABngACNAIAAladvQoxjc5OT0KBdzgE"
)
FOXY_COMRADE_ID = (
    "CAACAgIAAxkBAAIHiWlj6rwSyD3q5a4QkLyZqNkaO0GRAAJ-DAAC6-nRSIJMsuVXQZfvOAQ"
)
BODDY_BEAR_ID = "CAACAgIAAxkBAAIHOWlj4pbOW0myjJtmbIC33wq2E8WlAAL1AAP3AsgPR0aYYdFQyLE4BA"
TONY_STAR_ID = "CAACAgIAAxkBAAIHnGlj7Nr_vnQJ2odCQxZoBHSRvQ-iAAKFAAOmysgMiq1L6Q_-yXw4BA"
